### ISSUE TITLE
The desftruct of SEQUENCE needs to be before users os the accessors, specifically RESET-SEQUENCE

### ISSUE THREAD

**Issue by Yehouda** [fisxoj/factory-alien#3]
https://github.com/fisxoj/factory-alien/blob/0fb63f363bd54d4be1a0a0884d9a11fed6e64e8d/src/sequences.lisp#L26

**read-sequence** uses **(setf sequence-value)** before it is defined by the defstruct of **sequence**. 
https://github.com/fisxoj/factory-alien/blob/0fb63f363bd54d4be1a0a0884d9a11fed6e64e8d/src/sequences.lisp#L29

This should be fixed by moving the defstruct of *8seqeunce** before **read-seqeunce**.

At least on LispWorks, if you just compile and load, it errors on the setf. 

It works if you first evaluate the code, or compile it again, because then the structure is aleady defined.

**Comment by fisxoj** [comment]
Thanks for reporting this!

I'm overdue to revamp my CI flows for my lisp packages someday soon, and I hope I'll leave things in a less embarrassing state when that comes.
